@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Mar 05 10:03:18 +0800 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TB_my_mux_behav -key {Behavioral:sim_1:Functional:TB_my_mux} -tclbatch TB_my_mux.tcl -view E:/class/Master of ANU/6213_Digital Systems and Microprocessors/my_6213/lab1/my_mux/TB_my_mux_behav.wcfg -log simulate.log"
call xsim  TB_my_mux_behav -key {Behavioral:sim_1:Functional:TB_my_mux} -tclbatch TB_my_mux.tcl -view E:/class/Master of ANU/6213_Digital Systems and Microprocessors/my_6213/lab1/my_mux/TB_my_mux_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
